#!/usr/bin/env bash

# A tool for attaching and detaching devices to virtual machines, written in bash.
# Author: Eden Tyler-Moss https://github.com/ajmar
# License: GNU GPLv3

usage () {
	echo "# vmswitch" 1>&2
	echo -e "# Attach devices to and from a virtual machine\n"
	echo "Usage: vmswitch -adtADT [-lh]" 1>&2
	echo "Options:" 1>&2
	echo "	-l,			List usb devices with their number, id, and name." 1>&2
	echo "	-a DEVICE DOMAIN,	Attach the device to the VM." 1>&2
	echo "	-d DEVICE DOMAIN,	Detach the device from the VM." 1>&2
	echo "	-t DEVICE DOMAIN,	Toggle devices attachment to the VM." 1>&2
	echo "	-A DEVICE DOMAIN,	Add the device to the VM config." 1>&2
	echo "	-D DEVICE DOMAIN,	Remove the device from the VM config." 1>&2
	echo "	-T DEVICE DOMAIN,	Toggle the device's presence in the VM config." 1>&2
	echo -e "	-h,			Display usage information.\n" 1>&2
	echo -e "Notes:\nDEVICE can be either the number, id, or name of the usb device. Run vmswitch with -l to see these values.\nThe -a -d and -t options cannot be run at the same time, likewise with -A -D and -T.\nThe program will need elevated privlages to run (WIP, may not be handled correctly)." 1>&2
	echo -e "\nSee https://github.com/ajmar/vmswitch for more source code & more details." 1>&2
}

error () {
	local CLR="\e[1;0m"
	local RED="\e[1;31m"
	printf "${RED}[ERROR]${CLR} %s${CLR}\n" "$@" 1>&2
}

[ "$#" = '0' ] && error "No arguments supplied." 1>&2 && exit 1

list () {
	echo "Number	ID	Name"
	lsusb | cut -d " " -f 6- | cut -d ":" -f 2- | sed '/Linux Foundation/d' | sed 's/ /	/' | awk '{print NR-0 "	" $0}'
}
listvar="$(list)"
listfull="$(lsusb | cut -d " " -f 6- | sed '/Linux Foundation/d' | sed 's/ /	/' | awk '{print NR-0 "	" $0}')"

select_device () {
	if (( $(grep -c . <<<"$selectline") > 1 )); then
		error "Device name not precise enough." 1>&2 && exit; fi
	combined_id=$(echo "$selectline" | cut -d "	" -f 2- | cut -d "	" -f -1)
	device_id=$(echo "$combined_id" | cut -d ":" -f 2-)
	vendor_id=$(echo "$combined_id" | cut -d ":" -f -1)
	printf "<hostdev mode='subsystem' type='usb' managed='no'>
	<source>
	<vendor id='0x"$vendor_id"'/>
	<product id='0x"$device_id"'/>
	</source>
	</hostdev>" > /tmp/vmswitch.xml
}
select_name () {
	selectline=$(echo "$listfull" | awk -F"	" '$3 ~ /'$OPTARG'/{print}')
	[[ $selectline ]] && select_device || error "No matching device found." 1>&2 && exit
}
select_id () {
	selectline=$(echo "$listfull" | awk -F"	" '$2 ~ /'$OPTARG'/{print}')
	[[ $selectline ]] && select_device || select_name
}
select_num () { 
	selectline=$(echo "$listfull" | awk -F"	" '$1 ~ /^'$OPTARG'$/{print}')
	[[ $selectline ]] && select_device || select_id
}

attach_device () {
	select_num &&
	shift $((OPTIND - 1))
	[ "$#" = 0 ] && error "Not enough arguments supplied." 1>&2 && exit 1
	sudo virsh list --all | grep -E ""$1".*running" 1>/dev/null || (error "Is the guest running?"; exit 1)
	printf 'Attaching:'"\n""$selectline""\n"
	sudo virsh attach-device "$1" /tmp/vmswitch.xml 2>&1 | grep -q "is in use by" && error "Is the device already attached?" 1>&2 && exit 1 || exit
}

detach_device () {
	select_num &&
	shift $((OPTIND - 1))
	[ "$#" = 0 ] && error "Not enough arguments supplied." 1>&2 && exit 1
	sudo virsh list --all | grep -E ""$1".*running" >/dev/null || (error "Is the guest running?"; exit 1)
	printf 'Detaching:'"\n""$selectline""\n"
	sudo virsh detach-device "$1" /tmp/vmswitch.xml 2>&1 | grep -q "error: device not found" && error "Is the device already detached?" 1>&2 && exit 1 || exit
}

attach_device_perm () {
	select_num &&
	shift $((OPTIND - 1))
	[ "$#" = 0 ] && error "Not enough arguments supplied." 1>&2 && exit 1
	sudo virsh attach-device "$1" /tmp/vmswitch.xml --config 2>&1 | grep -q "device is already in the domain" && error "The device is already in the guest configuration." 1>&2 && exit 1 || printf 'Adding to config:'"\n""$selectline""\n" && exit
}

detach_device_perm () {
	select_num &&
	shift $((OPTIND - 1))
	[ "$#" = 0 ] && error "Not enough arguments supplied." 1>&2 && exit 1
	sudo virsh detach-device "$1" /tmp/vmswitch.xml --config 2>&1 | grep -q "device not present in domain" && error "The device is not in the guest configuration." 1>&2 && exit 1 || printf 'Removing from config:'"\n""$selectline""\n" && exit
}

while getopts ":la:d:t:A:D:T:h" opt; do
	case "$opt" in
		l)
			list
			;;
		a)
			attach_device "${@}"
			;;
		d)
			detach_device "${@}"
			;;
		t)
			select_num
			lsusb -v -d "$vendor_id"':'"$device_id" 2>&1 | grep -q 'get debug descriptor: Resource temporarily unavailable'
			status="$?"
			if [ "$status" = '1' ]
			then
				attach_device "${@}"
			else
				detach_device "${@}"
			fi
			;;
		A)
			attach_device_perm "${@}"
			;;
		D)
			detach_device_perm "${@}"
			;;
		T)
			permtoggle=$(attach_device_perm "${@}" 2>&1)
			echo "$permtoggle" | grep -q "The device is already in the guest configuration." && detach_device_perm "${@}" || echo "$permtoggle"
			;;
		h)
			usage && exit
			;;
		\?)
			error "Invalid option: -"$OPTARG"" 1>&2
			exit 1
			;;
		:)
			error "-"$OPTARG" Requires an argument." 1>&2
			exit 1
			;;
	esac
done

